name: OnPushChecker

on:
  push:
    branches: [ master ]

jobs:
  check_format:
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install llvm
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "20.1.0"
          directory: ./llvm
      - name: Update llvm files
        run: xcopy /Y /E /I /Q .\Bin\* .\llvm\
      - name: Install python3
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install python modules
        run: python3 -m pip install -r requirements.txt
      - name: Run format checker
        run: python3 build.py --build-type Debug --enable-format-check --donot-build-files --llvm-position ./llvm/bin/